{% set name = "xmlrpc-c" %}
{% set version = "1.54.06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ name }}/files/Xmlrpc-c%20Super%20Stable/{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: ae6d0fb58f38f1536511360dc0081d3876c1f209d9eaa54357e2bacd690a5640
  patches:
    - fix-cpp11.patch
    - fix-dumpvalue.patch
    - fix-asprintf.patch  # [osx]
    - fix-missing-includes.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - libxml2
    - libcurl
    - openssl
    - zlib
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/lib/libxmlrpc${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libxmlrpc++${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libxmlrpc_server${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libxmlrpc_server++${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libxmlrpc_client${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libxmlrpc_client++${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/xmlrpc.pc
    - test -f ${PREFIX}/lib/pkgconfig/xmlrpc++.pc
    - test -f ${PREFIX}/include/xmlrpc.h
    - test -f ${PREFIX}/include/xmlrpc_client.h
    - test -f ${PREFIX}/include/xmlrpc_server.h
    - xmlrpc-c-config --version

about:
  home: http://xmlrpc-c.sourceforge.net/
  license:  BSD-3-Clause
  license_file: doc/COPYING
  summary: A lightweight RPC library based on XML and HTTP.

extra:
  recipe-maintainers:
    - Tobias-Fischer
